// Run with: node --test test/build_backend_scripts_test.cjs
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { test } = require('node:test');

const root = path.resolve(__dirname, '..');
const powershell = process.platform === 'win32' ? 'powershell.exe' : 'pwsh';
const bash = process.platform === 'win32'
  ? ['C:/Program Files/Git/bin/bash.exe', 'C:/Program Files (x86)/Git/bin/bash.exe'].find(file => fs.existsSync(file))
  : 'bash';
const hasPowershell = !spawnSync(powershell, ['-NoProfile', '-NonInteractive', '-Command', 'exit 0']).error;
const hasBash = !!bash && !spawnSync(bash, ['--version']).error;
const bashPath = file => process.platform === 'win32'
  ? file.replace(/^([a-z]):/i, (_, drive) => `/${drive.toLowerCase()}`).replaceAll('\\', '/')
  : file;

function write(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function fixture(t, options = {}) {
  const tempBase = fs.realpathSync(os.tmpdir());
  const directory = fs.mkdtempSync(path.join(tempBase, 'fqapp build scripts '));
  t.after(() => {
    const resolved = fs.realpathSync(directory);
    assert.equal(path.dirname(resolved).toLowerCase(), tempBase.toLowerCase());
    assert.ok(path.basename(resolved).startsWith('fqapp build scripts '));
    // This is the single verified temporary fixture, never the real app tree.
    fs.rmSync(resolved, { recursive: true, force: true });
  });
  const app = path.join(directory, 'app with spaces');
  const source = path.join(directory, 'backend source');
  const fakeBin = path.join(directory, 'fake tools');
  const sdk = path.join(directory, 'sdk with spaces');
  const ndk = path.join(sdk, 'ndk', '29.0.1');
  const hostOS = options.hostOS || (process.platform === 'win32' ? 'windows' : process.platform === 'darwin' ? 'darwin' : 'linux');
  const hostArch = options.hostArch || 'amd64';
  const hostTag = `${hostOS === 'windows' ? 'windows' : hostOS === 'darwin' ? 'darwin' : 'linux'}-x86_64`;
  const prebuilt = path.join(ndk, 'toolchains', 'llvm', 'prebuilt', hostTag);
  const compiler = path.join(prebuilt, 'bin', `aarch64-linux-android21-clang${hostOS === 'windows' ? '.cmd' : ''}`);
  write(compiler, 'fixture compiler');
  fs.mkdirSync(path.join(prebuilt, 'sysroot', 'usr', 'include'), { recursive: true });
  for (const name of ['build_backend.ps1', 'build_backend.sh']) {
    write(path.join(app, 'scripts', name), fs.readFileSync(path.join(root, 'scripts', name), 'utf8').replaceAll('\r\n', '\n'));
  }
  write(path.join(source, 'main.go'), 'fixture');
  write(path.join(source, 'go.mod'), 'fixture');
  for (const name of ['config.json', 'filter.json', 'device_pool.example.json']) {
    write(path.join(source, 'config', name), 'upstream config');
    write(path.join(app, 'assets', 'config', name), 'app config');
  }
  for (const name of ['web', 'filters', 'plugins']) {
    write(path.join(source, name, 'existing.txt'), 'upstream runtime');
    write(path.join(source, name, 'nested directory', 'new.txt'), 'new upstream file');
    write(path.join(app, 'assets', name, 'existing.txt'), 'app runtime fix');
  }
  const binary = path.join(app, 'assets', 'bin', '');
  const library = path.join(app, 'android', 'app', 'src', 'main', 'jniLibs', 'arm64-v8a', 'liblegacy.so');
  write(binary, 'previous standalone');
  write(library, 'previous jni');
  // Match the escaped Windows SDK form generated by Android tooling.
  write(path.join(app, 'android', 'local.properties'), `sdk.dir=${sdk.replaceAll('\\', '\\\\').replaceAll(':', '\\:')}\n`);
  const fakeGo = path.join(fakeBin, 'go');
  write(fakeGo, fs.readFileSync(path.join(root, 'test', 'support', 'fake_backend_go.sh'), 'utf8').replaceAll('\r\n', '\n'));
  fs.chmodSync(fakeGo, 0o755);
  if (options.uname) {
    const fakeUname = path.join(fakeBin, 'uname');
    write(fakeUname, `#!/usr/bin/env bash\nprintf '%s\\n' '${options.uname}'\n`);
    fs.chmodSync(fakeUname, 0o755);
  }
  const log = path.join(directory, 'build.log');
  const report = path.join(directory, 'report.json');
  const env = {
    ...process.env,
    GOOS: 'caller-os', GOARCH: 'caller-arch', CGO_ENABLED: 'caller-cgo', CC: 'caller cc', CGO_CFLAGS: 'caller flags',
    ANDROID_NDK_HOME: options.localProperties ? '' : ndk,
    ANDROID_NDK_ROOT: '', ANDROID_HOME: '', ANDROID_SDK_ROOT: '',
    FQAPP_FAKE_LOG: log, FQAPP_FAKE_REPORT: report, FQAPP_FAKE_SOURCE: source,
    FQAPP_FAKE_HOST_OS: hostOS, FQAPP_FAKE_HOST_ARCH: hostArch,
    FQAPP_FAKE_FAILURE: options.failure || '',
    FQAPP_BUILD_JNI: options.jni === false ? '0' : '1',
    FQAPP_FORCE_RUNTIME: options.force ? '1' : '0', FQAPP_FORCE_CONFIG: options.force ? '1' : '0',
  };
  function runPowershell() {
    const result = spawnSync(powershell, ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', path.join(root, 'test', 'support', 'backend_build_harness.ps1')], {
      cwd: directory,
      env: { ...env, FQAPP_BUILD_SCRIPT: path.join(app, 'scripts', 'build_backend.ps1') },
      encoding: 'utf8', timeout: 30000,
    });
    assert.equal(result.status, 0, result.error?.message || result.stderr || result.stdout);
    const state = JSON.parse(fs.readFileSync(report, 'utf8'));
    assert.deepEqual(state.afterEnvironment, state.beforeEnvironment, 'build must restore all caller environment values');
    assert.equal(state.afterLocation, state.beforeLocation, 'build must restore the working directory');
    return { ...result, state, builds: fs.existsSync(log) ? fs.readFileSync(log, 'utf8').trim().split(/\r?\n/).map(line => JSON.parse(line.replace(/^\uFEFF/, ''))) : [] };
  }
  function runBash() {
    const flags = [];
    if (options.jni !== false) flags.push('--jni');
    if (options.force) flags.push('--force-runtime', '--force-config');
    const result = spawnSync(bash, ['-c', 'export PATH="$FQAPP_FAKE_BIN:$PATH"\nexec bash "$FQAPP_BUILD_SCRIPT" "$FQAPP_FAKE_SOURCE" "$@"', 'build-fixture', ...flags], {
      cwd: directory,
      env: {
        ...env, FQAPP_FAKE_LOG: bashPath(log), FQAPP_FAKE_SOURCE: bashPath(source),
        FQAPP_FAKE_BIN: bashPath(fakeBin), FQAPP_BUILD_SCRIPT: bashPath(path.join(app, 'scripts', 'build_backend.sh')),
      },
      encoding: 'utf8', timeout: 30000,
    });
    assert.ifError(result.error);
    const builds = fs.existsSync(log) ? fs.readFileSync(log, 'utf8').trim().split(/\r?\n/).map(line => {
      const [kind, GOOS, GOARCH, CGO_ENABLED, CC, CGO_CFLAGS] = line.split('\t');
      return { kind, GOOS, GOARCH, CGO_ENABLED, CC, CGO_CFLAGS };
    }) : [];
    return { ...result, builds };
  }
  function checkRuntime(force = false) {
    for (const name of ['web', 'filters', 'plugins']) {
      assert.equal(fs.readFileSync(path.join(app, 'assets', name, 'existing.txt'), 'utf8'), force ? 'upstream runtime' : 'app runtime fix');
      assert.equal(fs.readFileSync(path.join(app, 'assets', name, 'nested directory', 'new.txt'), 'utf8'), 'new upstream file');
    }
    assert.equal(fs.readFileSync(path.join(app, 'assets', 'config', 'config.json'), 'utf8'), force ? 'upstream config' : 'app config');
  }
  function checkNoBuildTemps() {
    assert.deepEqual(fs.readdirSync(path.dirname(binary)), ['']);
    assert.deepEqual(fs.readdirSync(path.dirname(library)), ['liblegacy.so']);
  }
  return { app, source, hostOS, hostArch, hostTag, compiler, prebuilt, binary, library, runPowershell, runBash, checkRuntime, checkNoBuildTemps };
}

for (const [shell, available, runName] of [['PowerShell', hasPowershell, 'runPowershell'], ['Bash', hasBash, 'runBash']]) {
  test(`${shell}: builds host and Android JNI with spaced paths while keeping app runtime fixes`, { skip: !available }, t => {
    const f = fixture(t);
    const result = f[runName]();
    assert.equal(result.status, 0, result.stderr || result.stdout);
    if (result.state) assert.equal(result.state.failure, null);
    assert.deepEqual(result.builds.map(b => [b.kind, b.GOOS, b.GOARCH, b.CGO_ENABLED]), [
      ['standalone', f.hostOS, f.hostArch, '0'], ['jni', 'android', 'arm64', '1'],
    ]);
    const jni = result.builds[1];
    assert.equal(jni.CC, `"${f.compiler.replaceAll('\\', '/')}"`);
    assert.equal(jni.CGO_CFLAGS, `-I"${f.prebuilt.replaceAll('\\', '/')}/sysroot/usr/include"`);
    assert.equal(fs.readFileSync(f.binary, 'utf8'), 'built standalone');
    assert.equal(fs.readFileSync(f.library, 'utf8'), 'built jni');
    f.checkRuntime();
    f.checkNoBuildTemps();
  });

  test(`${shell}: only explicit force flags overwrite app runtime and config`, { skip: !available }, t => {
    const f = fixture(t, { force: true, jni: false });
    const result = f[runName]();
    assert.equal(result.status, 0, result.stderr || result.stdout);
    if (result.state) assert.equal(result.state.failure, null);
    f.checkRuntime(true);
  });

  for (const kind of ['standalone', 'jni']) {
    for (const mode of ['fail', 'empty']) {
      test(`${shell}: ${kind} ${mode} preserves the previous output and cleans partial files`, { skip: !available }, t => {
        const f = fixture(t, { failure: `${kind}_${mode}` });
        const result = f[runName]();
        if (result.state) assert.ok(result.state.failure, 'build should throw');
        else assert.notEqual(result.status, 0, 'build should fail');
        assert.equal(fs.readFileSync(kind === 'jni' ? f.library : f.binary, 'utf8'), `previous ${kind}`);
        f.checkNoBuildTemps();
      });
    }
  }
}

test('PowerShell: discovers NDK from escaped SDK local.properties with spaces', { skip: !hasPowershell }, t => {
  const f = fixture(t, { localProperties: true });
  const result = f.runPowershell();
  assert.equal(result.state.failure, null);
  assert.equal(result.builds[1].CC, `"${f.compiler.replaceAll('\\', '/')}"`);
  f.checkNoBuildTemps();
});

test('Bash: selects the Darwin NDK toolchain on macOS hosts', { skip: !hasBash }, t => {
  const f = fixture(t, { hostOS: 'darwin', hostArch: 'arm64', uname: 'Darwin' });
  const result = f.runBash();
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.equal(result.builds[0].GOOS, 'darwin');
  assert.equal(result.builds[0].GOARCH, 'arm64');
  assert.match(result.builds[1].CC, /darwin-x86_64/);
  f.checkNoBuildTemps();
});
