// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cancelled_response`, `init_core`, `race_dispatch`, `release_inflight`, `resolve_runtime_dir`, `take_pre_cancelled`, `timeout_response`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Core`, `RaceOutcome`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

/// Backend core version.
Future<String> version() => RustLib.instance.api.crateApiVersion();

/// Idempotent initialization. A second call while running returns `"running"`.
///
/// `mock_upstream_origin` is empty in the shipping app. The host integration
/// test sets it to a local mock server so the real Dart -> FRB -> Rust path can
/// be exercised offline, without touching the network or a real device pool.
Future<String> init({
  required String configPath,
  required String poolPath,
  required String filterPath,
  required String runtimeDir,
  required int port,
  required String mockUpstreamOrigin,
}) => RustLib.instance.api.crateApiInit(
  configPath: configPath,
  poolPath: poolPath,
  filterPath: filterPath,
  runtimeDir: runtimeDir,
  port: port,
  mockUpstreamOrigin: mockUpstreamOrigin,
);

/// Stops the loopback adapter and drops the core.
///
/// Waits for an in-flight initialization first, so a shutdown issued during
/// `init` tears down the core that `init` just created rather than leaving it
/// running. Safe to call repeatedly.
Future<void> shutdown() => RustLib.instance.api.crateApiShutdown();

/// `"running"`, `"starting"` or `"failed: <message>"` - the same contract as
/// the Kotlin/JNI bridge this replaces.
Future<String> status() => RustLib.instance.api.crateApiStatus();

/// Base URL of the loopback adapter, for resource URLs (`absoluteUrl`).
Future<String> baseUrl() => RustLib.instance.api.crateApiBaseUrl();

/// Per-launch capability of the loopback adapter.
///
/// Every request the adapter accepts must carry it: as a `/_session/<cap>`
/// path prefix, an `Authorization: Bearer` header, or the session cookie the
/// entry URL sets. `base_url()` deliberately stays capability-free - the same
/// value is the FFI path root, and FFI calls never cross the socket. URLs
/// handed to HTTP clients instead (`/src/...`) must carry the prefix.
Future<String> sessionCapability() =>
    RustLib.instance.api.crateApiSessionCapability();

/// The single entry point for every backend call from Flutter.
///
/// `timeout_ms <= 0` means "no deadline". A cancelled or timed-out call drops
/// the dispatch future, which cancels the awaiting upstream request.
Future<BridgeResponse> request({
  required String requestId,
  required String method,
  required String path,
  required String query,
  required List<int> body,
  required PlatformInt64 timeoutMs,
}) => RustLib.instance.api.crateApiRequest(
  requestId: requestId,
  method: method,
  path: path,
  query: query,
  body: body,
  timeoutMs: timeoutMs,
);

/// Cancels an in-flight `request`. Returns true when a call was registered.
///
/// An unknown id is remembered as pre-cancelled so a cancel that beats the
/// request's own registration still takes effect.
Future<bool> cancel({required String requestId}) =>
    RustLib.instance.api.crateApiCancel(requestId: requestId);

class BridgeResponse {
  final int status;
  final String contentType;
  final Uint8List body;

  const BridgeResponse({
    required this.status,
    required this.contentType,
    required this.body,
  });

  @override
  int get hashCode => status.hashCode ^ contentType.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          contentType == other.contentType &&
          body == other.body;
}
