//! Golden-vector regression for the signing / device crypto port.
//!
//! Every expected value in testdata/*.json was generated by the reference implementation
//! implementation ( @ 947eafe + the two app patches). The vectors are
//! checked in so the Rust port is never compared against its own output.

use fqapi_core::device::crypto::{
    decrypt_register_key, encrypt_register_key_request, reverse_hex, tt_encrypt,
};
use fqapi_core::sign::argus::{
    argus_body_hash, argus_encrypt, argus_encrypt_enc_pb, argus_get_sign, argus_query_hash,
    ArgusBeanStyle, ArgusParams,
};
use fqapi_core::sign::ladon::{ladon_encrypt, ladon_encrypt_raw};
use fqapi_core::sign::protobuf::ProtoBuf;
use fqapi_core::sign::simon::{simon_dec, simon_enc, simon_key_expansion};
use fqapi_core::sign::sm3::sm3_hash;
use serde_json::Value;

fn vectors() -> Value {
    let raw = include_str!("../testdata/vectors.json");
    serde_json::from_str(raw).expect("vectors.json")
}

fn device_vectors() -> Value {
    let raw = include_str!("../testdata/device_vectors.json");
    serde_json::from_str(raw).expect("device_vectors.json")
}

fn parse_u64(s: &str) -> u64 {
    s.parse::<u64>().expect("decimal u64")
}

#[test]
fn sm3_matches_go_vectors() {
    let v = vectors();
    let long: Vec<u8> = vec![b'a'; 100];
    let cases: Vec<(&str, Vec<u8>)> = vec![
        ("empty", Vec::new()),
        ("abc", b"abc".to_vec()),
        ("zero16", vec![0u8; 16]),
        ("long", long),
        ("query", b"aid=1967&device_id=123&iid=456".to_vec()),
    ];
    for (name, input) in cases {
        let got = hex::encode(sm3_hash(&input));
        let want = v["sm3"][name].as_str().unwrap();
        assert_eq!(got, want, "sm3[{name}]");
    }
}

#[test]
fn simon_matches_go_vectors() {
    let v = vectors();
    let pt = [
        parse_u64(v["simon"]["pt"][0].as_str().unwrap()),
        parse_u64(v["simon"]["pt"][1].as_str().unwrap()),
    ];
    let k = [
        parse_u64(v["simon"]["k"][0].as_str().unwrap()),
        parse_u64(v["simon"]["k"][1].as_str().unwrap()),
        parse_u64(v["simon"]["k"][2].as_str().unwrap()),
        parse_u64(v["simon"]["k"][3].as_str().unwrap()),
    ];
    let ct = simon_enc(pt, k);
    assert_eq!(ct[0], parse_u64(v["simon"]["ct"][0].as_str().unwrap()));
    assert_eq!(ct[1], parse_u64(v["simon"]["ct"][1].as_str().unwrap()));

    var_keyexp_last(k, &v);
    assert_eq!(simon_dec(ct, k), pt, "simon round trip");
}

fn var_keyexp_last(k: [u64; 4], v: &Value) {
    let mut key = [0u64; 72];
    key[0] = k[0];
    key[1] = k[1];
    key[2] = k[2];
    key[3] = k[3];
    simon_key_expansion(&mut key);
    for (i, want) in v["simon_keyexp_last"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        assert_eq!(
            key[68 + i],
            parse_u64(want.as_str().unwrap()),
            "keyexp[{}]",
            68 + i
        );
    }
}

#[test]
fn ladon_matches_go_vectors() {
    let v = vectors();
    let rb = hex::decode(v["ladon"]["randomBytes"].as_str().unwrap()).unwrap();
    let got = ladon_encrypt(
        v["ladon"]["khronos"].as_i64().unwrap(),
        v["ladon"]["lcId"].as_i64().unwrap(),
        v["ladon"]["aid"].as_i64().unwrap(),
        &rb,
    );
    assert_eq!(got, v["ladon"]["result"].as_str().unwrap());

    let raw = ladon_encrypt_raw(
        v["ladon_raw"]["md5"].as_str().unwrap(),
        v["ladon_raw"]["data"].as_str().unwrap().as_bytes(),
    );
    assert_eq!(hex::encode(raw), v["ladon_raw"]["result"].as_str().unwrap());
}

#[test]
fn argus_hashes_match_go_vectors() {
    let v = vectors();
    assert_eq!(
        hex::encode(argus_body_hash("")),
        v["argus_bodyhash"]["null"].as_str().unwrap()
    );
    assert_eq!(
        hex::encode(argus_query_hash("")),
        v["argus_queryhash"]["null"].as_str().unwrap()
    );
    assert_eq!(
        hex::encode(argus_query_hash("aid=1967&device_id=123")),
        v["argus_queryhash"]["query"].as_str().unwrap()
    );
}

#[test]
fn argus_enc_pb_matches_go_vector() {
    let v = vectors();
    let input = hex::decode(v["argus_encpb"]["in"].as_str().unwrap()).unwrap();
    let out = argus_encrypt_enc_pb(&input, input.len() + 8);
    assert_eq!(hex::encode(out), v["argus_encpb"]["out"].as_str().unwrap());
}

/// Deterministic bean used by the Go golden vectors.
fn build_test_bean() -> ProtoBuf {
    let mut bean = ProtoBuf::new();
    bean.put_varint(1, 1_077_940_818);
    bean.put_varint(2, 2);
    bean.put_varint(3, 305_419_896);
    bean.put_utf8(4, "1967");
    bean.put_utf8(5, "test_device_id");
    bean.put_utf8(6, "1611921764");
    bean.put_utf8(7, "");
    bean.put_utf8(8, "");
    bean.put_varint(9, 0);
    bean.put_utf8(10, "");
    bean.put_utf8(11, "");
    bean.put_varint(12, 1_700_000_000 << 1);
    bean.put_bytes(13, &argus_body_hash(""));
    bean.put_bytes(
        14,
        &argus_query_hash("aid=1967&device_id=test_device_id&iid=456"),
    );

    let mut sub15 = ProtoBuf::new();
    sub15.put_varint(1, 1);
    sub15.put_varint(2, 1);
    sub15.put_varint(3, 1);
    sub15.put_varint(7, 0xC792_ECCC);
    bean.put_protobuf(15, &sub15);

    bean.put_utf8(16, "");
    bean.put_utf8(20, "none");
    bean.put_varint(21, 738);

    let mut sub23 = ProtoBuf::new();
    sub23.put_utf8(1, "NX551J");
    sub23.put_varint(2, 8196);
    sub23.put_varint(4, 0x80E0_D800);
    bean.put_protobuf(23, &sub23);

    bean.put_varint(25, 2);
    bean
}

#[test]
fn protobuf_and_legacy_argus_match_go_vectors() {
    let v = vectors();
    let bean = build_test_bean();
    assert_eq!(
        hex::encode(bean.to_buf()),
        v["protobuf_bean"].as_str().unwrap()
    );
    assert_eq!(
        argus_encrypt(&bean),
        v["argus_encrypt"]["result"].as_str().unwrap()
    );
}

/// x-argus 551 golden vectors. field3 is a per-call nonce, so it is recovered
/// from the trusted golden output (genuine round trip) and fed back in; that
/// still proves every fixed bean field, wire type and framing constant.
#[test]
fn argus_551_matches_go_vectors() {
    let golden: [(&str, i64, &str); 4] = [
        ("aid=1967&device_id=dev_aaaaaaaa&iid=111", 1_700_000_000,
         "8oHyrVYEy1xDCDlx64ko40qC6JC9VYY/ZkjJzEl50iSFDw8Yfph1hupLxfKrA9GswSEz0Yi4goA7OQ4u+H8ECdOaQDL4GduQ3LULSq9Q4iSEGbS3L6G24GXChtnmPr6n46M2PLlKpXvF7uE0lhH4yD+X69FpdM41gQwx5Y5U3NdwXFaxlqYFszyp7dlUE6BEBWqwDsiAH8Jk9TGKr/jfHt4fVmMc9zRyNRdGeV0x6aP//x7aV+8Po8a/9KK3UNG5KEpmIgzRT6NUttkBP9gRNUh3"),
        ("aid=1967&device_id=dev_bbbbbbbbbbbbbbbb&iid=222", 1_700_000_001,
         "8oGWgilKQHD4eCdd0VB0vBSbTAkv/3xWE2YWJkxic35CgXkxrUlMTz05HJAak5b5Xx9yxohnoAAcEX//MI9t7XBBtnPwOTaJzkJgBLaYOOotfI7YuqhsEbE5BB363bhKz/Qw/+MI5gH6pgdAXfsRj68u7Qwu3gqCY1NYstqNZFFVrph7dWtXDBYM1aoVEyfkYD2haoaOr9D/gl1zdzAAzbW7we6lr9/zFApbuNsbr2dagdUrQc51QNN0HBOtIkpVBVunDwXM8qR271Ei+Pa4EgKy"),
        ("aid=1967&device_id=X&iid=333", 1_234_567_890,
         "8oEOCRTb0LQf+M+MsliYu4M9kBzAlzXvFgL/Ub198hyoBGxYfNXLAENmH+K/10JQ+Rbhm2zRxNtNv5wVd885xcb6C6F10zp/9jVeGHGz8plz8W3UXHHNrFKjJptjQElGDbyaVLSKt56+HfwO7ENYMfjVv/5PNi1upVciiHqyOPDDAtwi/fZkwBoU1kC7RolMOuedn4lCg/s0CjnNvxFT0QpF/K0yoW3Zpu30tkadIET7WbZ3+7KT3c1yAA6RKWI4mmw="),
        ("aid=1967&device_id=test_device_id&iid=456&version_name=6.5.1.32", 1_700_000_000,
         "8oHu8LnZm0OtJJIaSr1427D+yeH70h5aZTVjoSW7MfFi/hk1LhjTqsEEWYpwcHfK4/2SXuJxTtopRcPeHzVpeFpUD4B4yxEG7REejpCZ1OqeAaLsw/lMebwUjUHrUjnAZCKq0QyimnwdiTiYIsH3GfiK/xlPcFcARqwX7RkI1qnnWUgiJVDEacSm8yhBat6MvDVOa7+U2MgcLu7Q26pFzX8VX5F+ryP76ETs1nRGLmlhHkwyiKb6CETstvGQnJgocgZBNNvlHD2/P+4LWjFMvhNK"),
    ];

    for (query, ts, want) in golden {
        let f3 = recover_argus551_field3(want);
        let got = argus_get_sign(&ArgusParams {
            query_string: query.to_string(),
            stub_hex: String::new(),
            timestamp: ts,
            aid: 1967,
            license_id: 1_611_921_764,
            device_id: fqapi_core::sign::query_param(query, "device_id").unwrap_or_default(),
            install_id: String::new(),
            style: ArgusBeanStyle::ArgusBean551,
            rand_field: f3,
        });
        assert_eq!(got, want, "argus551 query={query} ts={ts}");
    }
}

/// Reverses an x-argus 551 blob back to its bean and extracts field 3 (tag 0x18).
fn recover_argus551_field3(argus_b64: &str) -> i32 {
    use base64::Engine as _;
    let raw = base64::engine::general_purpose::STANDARD
        .decode(argus_b64)
        .expect("golden base64");
    let sign_key =
        hex::decode("fc78e0a9657a0c748ce51559903ccf03510e51d3cff232d71343e88a321c5304").unwrap();
    let aes_key = hex::decode("d31e3718288a1027baab59f146a09a9c").unwrap();
    let aes_iv = hex::decode("ea180a0336ed352fcd24e4d50018ae54").unwrap();

    let ct = &raw[2..];
    let pt = fqapi_core::crypto::aes_cbc_decrypt(ct, &aes_key, &aes_iv);
    let pad = *pt.last().unwrap() as usize;
    let body = &pt[..pt.len() - pad];
    let body = &body[..body.len() - 2];

    let mut rev = body.to_vec();
    rev.reverse();
    let mut un = vec![0u8; rev.len()];
    un[..8].copy_from_slice(&rev[..8]);
    for i in 8..rev.len() {
        un[i] = rev[i] ^ rev[i % 8];
    }
    let enc_pb = &un[8..];
    let enc_pb = &enc_pb[..enc_pb.len() / 16 * 16];

    let mut kl = [0u64; 4];
    for i in 0..4 {
        let mut b = [0u8; 8];
        b.copy_from_slice(&sign_key[i * 8..i * 8 + 8]);
        kl[i] = u64::from_le_bytes(b);
    }
    let mut proto = Vec::with_capacity(enc_pb.len());
    for chunk in enc_pb.chunks(16) {
        let mut a = [0u8; 8];
        let mut b = [0u8; 8];
        a.copy_from_slice(&chunk[..8]);
        b.copy_from_slice(&chunk[8..]);
        let p = simon_dec([u64::from_le_bytes(a), u64::from_le_bytes(b)], kl);
        proto.extend_from_slice(&p[0].to_le_bytes());
        proto.extend_from_slice(&p[1].to_le_bytes());
    }

    let mut i = 0;
    while i < proto.len() {
        if proto[i] == 0x18 {
            let mut v: u64 = 0;
            let mut shift = 0u32;
            let mut j = i + 1;
            loop {
                let b = proto[j];
                v |= ((b & 0x7f) as u64) << shift;
                j += 1;
                if b < 0x80 {
                    break;
                }
                shift += 7;
            }
            return v as i32;
        }
        i += 1;
    }
    panic!("field3 tag not found");
}

#[test]
fn reverse_hex_matches_go_vectors() {
    let v = device_vectors();
    for (id, want) in v["reversehex"].as_object().unwrap() {
        assert_eq!(&reverse_hex(id), want.as_str().unwrap(), "reverseHex({id})");
    }
}

#[test]
fn decrypt_register_key_matches_go_vector() {
    let v = device_vectors();
    let got = decrypt_register_key(v["decryptkey"]["input_b64"].as_str().unwrap()).unwrap();
    // The reference implementation test also compares case-insensitively ("the key is stored as
    // uppercase hex"); the decrypted bytes are identical either way.
    assert_eq!(
        hex::encode(&got).to_uppercase(),
        v["decryptkey"]["expect_hex"]
            .as_str()
            .unwrap()
            .to_uppercase()
    );
    assert_eq!(
        hex::encode(&got),
        v["decryptkey"]["expect_plain"]
            .as_str()
            .map(|s| hex::encode(s.as_bytes()))
            .unwrap_or_default()
    );
}

#[test]
fn decrypt_register_key_rejects_unaligned_upstream_ciphertext() {
    use base64::Engine as _;
    let malformed = base64::engine::general_purpose::STANDARD.encode([0u8; 17]);
    assert!(decrypt_register_key(&malformed)
        .unwrap_err()
        .contains("not block-aligned"));
}

#[test]
fn decrypt_register_key_rejects_empty_ciphertext() {
    use base64::Engine as _;
    // 16 bytes = IV only: block-aligned, but decrypting it would yield an
    // empty key instead of an error.
    let malformed = base64::engine::general_purpose::STANDARD.encode([0u8; 16]);
    assert!(decrypt_register_key(&malformed)
        .unwrap_err()
        .contains("empty"));
}

#[test]
fn encrypt_register_key_request_matches_go_vector() {
    let v = device_vectors();
    let got = encrypt_register_key_request(
        v["registerkey_req"]["device_id"].as_str().unwrap(),
        Some(v["registerkey_req"]["iv"].as_str().unwrap().as_bytes()),
    )
    .unwrap();
    assert_eq!(got, v["registerkey_req"]["content"].as_str().unwrap());
}

#[test]
fn tt_encrypt_matches_go_vector() {
    let v = device_vectors();
    let mut random32 = [0u8; 32];
    let decoded = hex::decode(v["ttencrypt"]["random32"].as_str().unwrap()).unwrap();
    random32.copy_from_slice(&decoded);
    let got = tt_encrypt(
        v["ttencrypt"]["data"].as_str().unwrap().as_bytes(),
        Some(random32),
    )
    .unwrap();
    assert_eq!(hex::encode(got), v["ttencrypt"]["result"].as_str().unwrap());
}
