#!/usr/bin/env python3
"""Generate checked-in app icons from assets/branding/app_icon_source.png.

Requires Pillow: python -m pip install Pillow
From the repository root: python scripts/generate_app_icons.py
Normal Flutter / Android builds use the generated files without running this.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageOps


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets/branding/app_icon_source.png"
RES = ROOT / "android/app/src/main/res"
PAPER = (255, 254, 240)
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}

# Android masks the central 72dp of a 108dp adaptive layer. Keep the drawing
# at 60dp so circular launchers retain the bookmark and the tomato outline.
ADAPTIVE_SIZE = 108
ARTWORK_SIZE = 60
VISIBLE_SIZE = 72


def save_png(image: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, optimize=True)
    print(f"{path.relative_to(ROOT).as_posix()} ({image.width}x{image.height})")


def place_artwork(source: Image.Image, size: int, artwork_size: int,
                  *, transparent: bool = False) -> Image.Image:
    background = (*PAPER, 0 if transparent else 255)
    canvas = Image.new("RGBA", (size, size), background)
    artwork = source.resize((artwork_size, artwork_size), Image.Resampling.LANCZOS)
    offset = (size - artwork_size) // 2
    canvas.alpha_composite(artwork, (offset, offset))
    return canvas


def main() -> None:
    with Image.open(SOURCE) as original:
        source = ImageOps.exif_transpose(original).convert("RGBA")
    if source.width != source.height or source.width < 512:
        raise SystemExit("Use a square source image of at least 512x512 pixels.")

    # Legacy and adaptive launchers use the same visible artwork proportions.
    legacy_size = VISIBLE_SIZE * 16
    legacy = place_artwork(source, legacy_size, ARTWORK_SIZE * 16)
    round_legacy = legacy.copy()
    round_mask = Image.new("L", legacy.size, 0)
    ImageDraw.Draw(round_mask).ellipse(
        (0, 0, legacy_size - 1, legacy_size - 1), fill=255)
    round_legacy.putalpha(round_mask)

    for density, scale in DENSITIES.items():
        directory = RES / f"mipmap-{density}"
        size = round(48 * scale)
        save_png(legacy.resize((size, size), Image.Resampling.LANCZOS).convert("RGB"),
                 directory / "ic_launcher.png")
        save_png(round_legacy.resize((size, size), Image.Resampling.LANCZOS),
                 directory / "ic_launcher_round.png")
        foreground = place_artwork(source, round(ADAPTIVE_SIZE * scale),
                                   round(ARTWORK_SIZE * scale), transparent=True)
        save_png(foreground, directory / "ic_launcher_foreground.png")

    adaptive = RES / "mipmap-anydpi-v26"
    adaptive.mkdir(parents=True, exist_ok=True)
    adaptive_xml = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_app_icons.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
'''
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        (adaptive / name).write_text(adaptive_xml, encoding="utf-8")

    (RES / "values").mkdir(parents=True, exist_ok=True)
    paper_hex = "#" + "".join(f"{value:02X}" for value in PAPER)
    (RES / "values/ic_launcher_background.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/generate_app_icons.py. -->\n'
        f'<resources>\n    <color name="ic_launcher_background">{paper_hex}</color>\n'
        '</resources>\n', encoding="utf-8")

    save_png(source.resize((512, 512), Image.Resampling.LANCZOS),
             ROOT / "assets/images/app_logo.png")
    save_png(source.resize((64, 64), Image.Resampling.LANCZOS),
             ROOT / "assets/web/favicon.png")


if __name__ == "__main__":
    main()
